In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [3]:
df=pd.read_csv('data/train.csv')
missing=df.isnull().sum()
missing[missing>0]

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [4]:
num_col=df.select_dtypes(include=['int64','float64']).columns
cat_col=df.select_dtypes(include=['object']).columns
df[num_col].head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000


In [5]:
df[cat_col].head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal


In [6]:
for col in num_col:
    df[col]=df[col].fillna(df[col].mean())
for col in cat_col:
    df[col]=df[col].fillna(df[col].mode()[0])

In [7]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [8]:
df=pd.get_dummies(
    df,
    columns=cat_col,
    drop_first=True,
    dtype=int
)

In [9]:
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,0,1,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,0,1,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,0,1,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,0,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,0,1,0,0,0,1,0


In [10]:
X=df.drop('SalePrice',axis=1)
y=df['SalePrice']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

Feature Scaling

In [12]:
scaler=StandardScaler()
X_train_Scaled=scaler.fit_transform(X_train)
X_test_Scaled=scaler.transform(X_test)

In [13]:
X_train_Scaled[:5]

array([[-1.11928402, -0.8667643 , -0.01288179, ..., -0.12510865,
         0.46001984, -0.30263639],
       [ 0.79046412,  0.07410996, -0.5027726 , ..., -0.12510865,
         0.46001984, -0.30263639],
       [-0.21615189, -0.63154574, -0.14648837, ..., -0.12510865,
         0.46001984, -0.30263639],
       [ 0.16250507, -0.16110861, -0.45823707, ..., -0.12510865,
         0.46001984, -0.30263639],
       [-0.82294379, -0.16110861, -0.90359235, ..., -0.12510865,
         0.46001984, -0.30263639]], shape=(5, 245))

In [14]:
X_test_Scaled[:5]

array([[ 0.38123238, -0.8667643 , -0.01288179, ..., -0.12510865,
         0.46001984, -0.30263639],
       [ 0.88218848,  0.07410996,  1.23411301, ..., -0.12510865,
         0.46001984, -0.30263639],
       [-0.74533088, -0.63154574, -0.63637918, ..., -0.12510865,
         0.46001984, -0.30263639],
       [-0.48897306, -0.16110861, -0.90359235, ..., -0.12510865,
         0.46001984, -0.30263639],
       [ 0.71990693, -0.8667643 ,  0.83329325, ..., -0.12510865,
         0.46001984, -0.30263639]], shape=(5, 245))

In [15]:
model=LinearRegression()
model.fit(X_train_Scaled,y_train)
prediction = model.predict(X_test_Scaled)
prediction[:5]

array([157801.18216784, 349340.85325807,  86498.71780403, 173972.18425209,
       317563.56247628])

In [16]:
mae=mean_absolute_error(y_test,prediction)
rmse=np.sqrt(mean_squared_error(y_test,prediction))
r2=r2_score(y_test,prediction)

In [17]:
mae

20230.085415737492

In [18]:
rmse

np.float64(51396.87552006145)

In [19]:
r2

0.655602807250953

In [21]:
tr=model.score(X_train,y_train)
tr

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


-5047276.805128047

In [23]:
te=model.score(X_test,y_test)
te

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


-3017865.803101713

In [30]:
comparison=pd.DataFrame(
    {"Actual":y_test, "Predicted":prediction})
comparison.head(10)

,Actual,Predicted
892,154500,157801.182168
1105,325000,349340.853258
413,115000,86498.717804
522,159000,173972.184252
1036,315500,317563.562476
614,75500,66677.117955
218,311500,235613.882772
1160,146000,146365.460292
649,84500,57710.754651
887,135500,153922.235944


In [28]:
residual=y_test-prediction
residual.head()

892     -3301.182168
1105   -24340.853258
413     28501.282196
522    -14972.184252
1036    -2063.562476
Name: SalePrice, dtype: float64